syntax = "proto3";

package action_proto;

import "pmodel.proto";

message ActionProto {
  oneof kind {
    uint32 move_effect_up = 1;
    uint32 move_effect_down = 2;
    SetFloatProto set_float = 3;
    SetUintProto set_uint = 4;
    TypeFieldProto set_child = 5;
    TypeFieldProto add_child = 6;
    IndexFieldProto delete_child = 7;
  }
}

message IndexFieldProto {
  oneof kind {
    uint32 track = 1;
    uint32 placed_note = 2;
    uint32 track_placement = 3;
    uint32 effect = 4;
    uint32 generator = 5;
  }
}

message TypeFieldProto {
  oneof kind {
    pmodel.ScaleValueProto key = 1;
    pmodel.ScaleProto scale = 2;
    pmodel.TrackPlacementProto track_placement = 3;
    pmodel.PitchNameProto pitch_name = 4;
    string project_name = 5;
    pmodel.ScaleValueProto scale_value = 6;
    pmodel.TrackProto track = 7;
    pmodel.PlacedNoteProto placed_note = 8;
    pmodel.WaveTypeProto wave = 9;
    pmodel.AdsrEnvelopeProto envelope = 10;
    pmodel.AntiAliasingModeProto anti_aliasing_mode = 11;
    pmodel.EqTypeProto eq_type = 12;
    pmodel.EffectInstanceProto effect = 13;
    pmodel.FloatOptionProto clipped_duration = 14;
    bool mute = 15;
    int32 octave = 16;
    pmodel.FilenameTreeProto sample_tree = 17;
    pmodel.FileTreeConfigProto sample_tree_config = 18;
  }
}

message SetFloatProto {
  string key = 1;
  float value = 2;
}

message SetUintProto {
  string key = 1;
  uint32 value = 2;
}

message ReversibleActionProto {
  ActionProto forward = 1;
  ActionProto reverse = 2;
  SelectorProto selector = 3;
  bool is_compacted = 4; // TODO: what to do about this? Don't send over the wire?
}

message SelectorProto {
  oneof kind {
    uint32 root = 1; // dummy value
    uint32 track = 2;
    IndexPair note = 3;
    uint32 mixer = 4;
    IndexPair effect = 5;
    uint32 generator = 6;
    uint32 track_placement = 7;
    IndexPair oscillator = 8;
  }

  message IndexPair {
    uint32 first = 1;
    uint32 second = 2;
  }
}

