syntax = "proto3";

package action_proto;

import "pmodel.proto";

message ActionProto {
  oneof kind {
    SetFloatProto set_float = 3;
    SetUintProto set_uint = 4;
    IndexFieldProto set_index = 5;
    TypeFieldProto set_child = 6;
    TypeFieldProto add_child = 7;
    IndexFieldProto delete_child = 8;
    MoveFieldProto move_child = 9;
    MultiIndexFieldProto delete_children = 10;
    MultiTypeFieldProto set_children = 11;
  }
}

message IndexFieldProto {
  oneof kind {
    uint32 track = 1;
    uint32 placed_note = 2;
    uint32 placement = 3;
    uint32 effect = 4;
    uint32 mixer = 7;
    uint32 generator = 5;
    uint32 sample = 6;
  }
}

// Send Multiple IndexFields at once
message MultiIndexFieldProto {
  // `kind` field required for easy proto conversion.
  MultiIndexFieldKind kind = 1;
  repeated uint32 values = 2;
}

enum MultiIndexFieldKind {
  UnknownIndexFieldKind = 0;
  TrackIndexFieldKind = 1;
  PlacedNoteIndexFieldKind = 2;
  PlacementIndexFieldKind = 3;
  EffectIndexFieldKind = 4;
  MixerIndexFieldKind = 7;
  GeneratorIndexFieldKind = 5;
  SampleIndexFieldKind = 6;
}

message MoveFieldProto {
  IndexFieldProto from_field = 1;
  IndexFieldProto to_field = 2;
}

message TypeFieldProto {
  oneof kind {
    pmodel.ScaleValueProto key = 1;
    pmodel.ScaleProto scale = 2;
    pmodel.PlacementProto placement = 3;
    pmodel.PitchNameProto pitch_name = 4;
    string project_name = 5;
    pmodel.ScaleValueProto scale_value = 6;
    pmodel.TrackProto track = 7;
    pmodel.PlacedNoteProto placed_note = 8;
    pmodel.WaveTypeProto wave = 9;
    pmodel.AdsrEnvelopeProto envelope = 10;
    pmodel.AntiAliasingModeProto anti_aliasing_mode = 11;
    pmodel.EqTypeProto eq_type = 12;
    pmodel.EffectInstanceProto effect = 13;
    pmodel.FloatOptionProto clipped_duration = 14;
    bool mute = 15;
    int32 octave = 16;
    pmodel.FilenameTreeProto sample_tree = 17;
    pmodel.FileTreeConfigProto sample_tree_config = 18;
    pmodel.GeneratorInstanceProto generator = 19;
    pmodel.MixerChannelProto mixer_channel = 20;
    pmodel.PolyphonyModeProto polyphony_mode = 21;
    pmodel.NoiseTypeProto noise_type = 22;
  }
}

// Send multiple TypeFields at once.
message MultiTypeFieldProto {
  // `kind` field required for easy proto conversion.
  MultiTypeFieldKind kind = 1;
  repeated TypeFieldProto values = 2;
}

enum MultiTypeFieldKind {
  UnknownTypeFieldKind = 0;
  TrackTypeFieldKind = 1;
  PlacedNoteTypeFieldKind = 2;
  PlacementTypeFieldKind = 3;
  EffectTypeFieldKind = 4;
  GeneratorTypeFieldKind = 5;
}

message SetFloatProto {
  string key = 1;
  float value = 2;
}

message SetUintProto {
  string key = 1;
  uint32 value = 2;
}

message ReversibleActionProto {
  ActionProto forward = 1;
  ActionProto reverse = 2;
  SelectorProto selector = 3;
  bool is_compacted = 4; // TODO: what to do about this? Don't send over the wire?
}

message SelectorProto {
  oneof kind {
    uint32 root = 1; // dummy value
    uint32 track = 2;
    IndexPair note = 3;
    uint32 mixer = 4;
    IndexPair effect = 5;
    uint32 generator = 6;
    uint32 placement = 7;
    IndexPair oscillator = 8;
    IndexPair mixer_matrix_cell = 9;
    IndexPair lfo = 10;
    IndexPair generator_effect = 11;
    IndexPair envelope = 12;
    IndexPair mod_matrix_cell = 13;
  }

  message IndexPair {
    uint32 first = 1;
    uint32 second = 2;
  }
}

