syntax = "proto3";

package load_sample;

import "pmodel.proto";

service LoadSample {
  rpc LoadSample (LoadSampleRequest) returns (LoadSampleReply) {}

  rpc LoadSampleTree (LoadSampleTreeRequest) returns (LoadSampleTreeReply) {}
}

message LoadSampleRequest {
  string filename = 1;
}

message LoadSampleReply {
  pmodel.SampleProto sample = 1;
}

message LoadSampleTreeRequest {
  // Note: consider allowing the client to request a specific subtree.
}

message LoadSampleTreeReply {
  pmodel.FilenameTreeProto tree = 1;
}
