syntax = "proto3";

package pmodel;

message TrackProto {
  repeated PlacedNoteProto notes = 1;
}

message PlacedNoteProto {
  NoteProto note = 1;

  float offset = 2;
}

message NoteProto {
  PitchNameProto pitch_name = 1;

  float beats = 2;
}

message AdsrEnvelopeProto {
  float attack = 1;

  float decay = 2;

  float sustain = 3;

  float release = 4;
}

message PitchNameProto {
  ScaleValueProto scale_value = 1;

  int32 octave = 2;
}

enum WaveTypeProto {
  Unknown = 0;
  Sine = 1;
  Square = 2;
  Saw = 3;
  Triangle = 4;
}

enum ScaleValueProto {
  UnknownScaleValue = 0;
  AScaleValue = 1;
  ASharpScaleValue = 2;
  BScaleValue = 3;
  CScaleValue = 4;
  CSharpScaleValue = 5;
  DScaleValue = 6;
  DSharpScaleValue = 7;
  EScaleValue = 8;
  FScaleValue = 9;
  FSharpScaleValue = 10;
  GScaleValue = 11;
  GSharpScaleValue = 12;
}

enum ScaleProto {
    UnknownScale = 0;
    ChromaticScale = 1;
    MajorScale = 2;
    HarmonicMinorScale = 3;
    NaturalMinorScale = 4;
    PentatonicScale = 5;
}

