syntax = "proto3";

package pmodel;

message TrackProto {
  float bpm = 1;

  repeated SynthProto synth = 2;

  repeated SequenceProto sequence = 3;
}

message SequenceProto {
  float offset = 1;

  float volume = 2;

  uint32 synth_index = 3;

  repeated NoteProto note = 4;
}

message SynthProto {
  WaveTypeProto wave = 1;

  AdsrEnvelopeProto envelope = 2;

  float volume = 3;
}

message NoteProto {
  float semitones = 1;

  float beats = 2;
}

message AdsrEnvelopeProto {
  float attack = 1;

  float decay = 2;

  float sustain = 3;

  float release = 4;
}

message PitchNameProto {
  ScaleValueProto scale_value = 1;

  uint32 octave = 2;
}

enum WaveTypeProto {
  Unknown = 0;
  Sine = 1;
  Square = 2;
  Saw = 3;
  Triangle = 4;
}

enum ScaleValueProto {
  UnknownScaleValue = 0;
  AScaleValue = 1;
  ASharpScaleValue = 2;
  BScaleValue = 3;
  CScaleValue = 4;
  CSharpScaleValue = 5;
  DScaleValue = 6;
  DSharpScaleValue = 7;
  EScaleValue = 8;
  FScaleValue = 9;
  FSharpScaleValue = 10;
  GScaleValue = 11;
  GSharpScaleValue = 12;
}

