syntax = "proto3";

package pmodel;

message ProjectProto {
  string name = 1;

  repeated TrackProto tracks = 2;

  /// Ordered based on start_position.
  repeated TrackPlacementProto track_placements = 3;

  repeated SampleProto samples = 4;

  repeated GeneratorInstanceProto generators = 5;

  repeated MixerChannelProto mixer = 6;

  float bpm = 7;

  ModMatrixProto mod_matrix = 8;
}

message ModMatrixProto {
  uint32 rows = 1;

  uint32 cols = 2;

  repeated float matrix = 3;
}

message TrackProto {
  repeated PlacedNoteProto notes = 1;

  float offset = 2;
}

message TrackPlacementProto {
  uint32 track_id = 1;

  float offset = 2;

  optional float clipped_duration = 3;

  uint32 visual_placement = 4;
}

message SampleProto {
  bytes data = 1;

  float sample_rate = 2;
}

message MixerChannelProto {
  repeated EffectInstanceProto effects = 1;
}

message PlacedNoteProto {
  NoteProto note = 1;

  float offset = 2;
}

message NoteProto {
  PitchNameProto pitch_name = 1;

  float beats = 2;
}

message AdsrEnvelopeProto {
  float attack = 1;

  float decay = 2;

  float sustain = 3;

  float release = 4;
}

message PitchNameProto {
  ScaleValueProto scale_value = 1;

  int32 octave = 2;
}

message EffectInstanceProto {
  EffectMetaProto meta = 1;

  oneof effect {
    SimpleDelayProto simple_delay = 2;

    SimpleEqProto simple_eq = 3;

    SimpleCompressorProto simple_compressor = 4;

    ModDelayProto mod_delay = 5;
  }

}

message GeneratorInstanceProto {
  uint32 id = 1;

  GeneratorMetaProto meta = 2;

  oneof kind {
    SimpleWaveProto simple_wave = 3;
    NoiseProto noise = 4;
    SubSynthProto sub_synth = 5;
  };
}

message NoiseProto {
  NoiseConfigProto config = 1;
}

message NoiseConfigProto {
  NoiseTypeProto kind = 1;
}

enum NoiseTypeProto {
  UnknownNoiseType = 0;
  WhiteNoiseType = 1;
  BrownNoiseType = 2;
  PinkNoiseType = 3;
}

message SubSynthProto {
  SubSynthConfigProto config = 1;
}

message SubSynthConfigProto {
  repeated OscillatorConfigProto oscillators = 1; 
}

message OscillatorConfigProto {
  WaveTypeProto wave = 1;
  float volume = 2;
  float pan = 3;
  float coarse_detune = 4;
  float fine_detune = 5;
}

message GeneratorMetaProto {
  float volume = 1;

  bool mute = 2;

  float pan = 3;
}

message SimpleWaveProto {
  SimpleWaveConfigProto config = 1;
}

message SimpleWaveConfigProto {
  WaveTypeProto wave = 1;

  AdsrEnvelopeProto envelope = 2;

  uint32 osc_count = 3;

  float detune_cents = 4;

  AntiAliasingModeProto anti_aliasing_mode = 5;

  uint32 oversample_factor = 6;
}

message EffectMetaProto {
  uint32 id = 1;

  float wet = 2;

  bool mute = 3;
}

message SimpleDelayProto {
  DelayConfigProto config = 1;
}

message DelayConfigProto {
  float delay_ms = 1;

  float feedback = 2;
}

message SimpleEqProto {
  EqConfigProto config = 1;
}

message EqConfigProto {
  EqTypeProto kind = 1;

  float fc = 2;

  float q = 3;

  float gain = 4;
}

message SimpleCompressorProto {
  CompressorConfigProto config = 1;
}

message CompressorConfigProto {
  float threshold = 1;

  float attack_ms = 2;

  float release_ms = 3;

  float ratio = 4;

  float gain = 5;
}

message ModDelayProto {
  ModDelayConfigProto config = 1;
}

message ModDelayConfigProto {
  uint32 min_depth = 1;
  uint32 max_depth = 2;
  float freq = 3;
  WaveTypeProto lfo_type = 4;
}

enum WaveTypeProto {
  UnknownWaveType = 0;
  SineWaveType = 1;
  SquareWaveType = 2;
  SawWaveType = 3;
  TriangleWaveType = 4;
}

enum AntiAliasingModeProto {
  UnknownAntiAliasingMode = 0;
  OffAntiAliasingMode = 1;
  OversampleAntiAliasingMode = 2;
  AdditiveAntiAliasingMode = 3;
}

enum ScaleValueProto {
  UnknownScaleValue = 0;
  CScaleValue = 1;
  CSharpScaleValue = 2;
  DScaleValue = 3;
  DSharpScaleValue = 4;
  EScaleValue = 5;
  FScaleValue = 6;
  FSharpScaleValue = 7;
  GScaleValue = 8;
  GSharpScaleValue = 9;
  AScaleValue = 10;
  ASharpScaleValue = 11;
  BScaleValue = 12;
}

enum ScaleProto {
  UnknownScale = 0;
  ChromaticScale = 1;
  MajorScale = 2;
  HarmonicMinorScale = 3;
  NaturalMinorScale = 4;
  PentatonicScale = 5;
}

enum EqTypeProto {
  UnknownEqType = 0;
  SimpleResonatorEqType = 1;
  SmithAngellResonatorEqType = 2;
  SimpleFirstOrderLowPassEqType = 3;
  SimpleFirstOrderHighPassEqType = 4;
  SimpleSecondOrderLowPassEqType = 5;
  SimpleSecondOrderHighPassEqType = 6;
  SimpleSecondOrderResonatorEqType = 7;
  SimpleSecondOrderBandStopEqType = 8;
  FirstOrderAllPassEqType = 13;
  SecondOrderAllPassEqType = 14;
  LinkwitzRileySecondOrderLowPassEqType = 15;
  LinkwitzRileySecondOrderHighPassEqType = 16;
  FirstOrderAllPoleEqType = 17;
  ParametricSecondOrderNonConstantQEqType = 18;
  LowShelvingFirstOrderEqType = 19;
  HighShelvingFirstOrderEqType = 20;
  ParametricSecondOrderConstantQEqType = 21;
}

// Wrapper to allow passing Option<f32> as arguments for enums in protos.
message FloatOptionProto {
  optional float value = 1;
}
