syntax = "proto3";

package save_load;

import "pmodel.proto";

service SaveLoad {
  rpc SaveProject (SaveProjectRequest) returns (SaveProjectReply) {}
  rpc LoadProjectList (LoadProjectListRequest) returns (LoadProjectListReply) {}
  rpc LoadProject (LoadProjectRequest) returns (LoadProjectReply) {}
}

message SaveProjectRequest {
  string name = 1;
  pmodel.ProjectProto project = 2;
}

message SaveProjectReply {
}

message LoadProjectListRequest {
}

message LoadProjectListReply {
  repeated string project_names = 1;
}

message LoadProjectRequest {
  string name = 1;
}

message LoadProjectReply {
  pmodel.ProjectProto project = 1;
}
