syntax = "proto3";

package save_track;

import "pmodel.proto";

service SaveTrack {
  rpc SaveTrack (SaveTrackRequest) returns (SaveTrackReply) {}
}

service LoadTrackList {
  rpc LoadTrackList (LoadTrackListRequest) returns (LoadTrackListReply) {}
}

service LoadTrack {
  rpc LoadTrack (LoadTrackRequest) returns (LoadTrackReply) {}
}

message SaveTrackRequest {
  string name = 1;
  pmodel.TrackProto track = 2;
}

message SaveTrackReply {
}

message LoadTrackListRequest {
}

message LoadTrackListReply {
  repeated string names = 1;
}

message LoadTrackRequest {
  string name = 1;
}

message LoadTrackReply {
  pmodel.TrackProto track = 1;
}
