[package]
name = "mesic"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
assert_float_eq = "1.1.4"

[dependencies]
dasp_envelope = { version = "0.11.0", features = ["peak", "rms"] }
dasp_frame = "0.11.0"
dasp_graph = { path = "../vendor/dasp_graph", features = ["node-boxed"] }
dasp_ring_buffer = "0.11.0"
dasp_rms = "0.11.0"
dasp_slice = "0.11.0"
lazy_static = "1.5.0"
log = "0.4.27"
ordered-float = "5.0.0"
petgraph = "0.5" # Needs to match version used by dasp_graph.
ringbuffer = "0.15.0"
rustfft = { version = "6.3.0", features = ["wasm_simd"] }
shared = { path = "../shared" }
state = { version = "0.1.0", path = "../state" }
rand = "0.8"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
