[package]
name = "rng"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.27"
rand = "0.8"
wasm-bindgen-futures = "0.4.50"

[dependencies.getrandom]
version = "0.2"
features = ["js"]

[[bin]]
name = "rng-bin"  
path = "src/main.rs"
