[package]
name = "hydric"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
leptos = { version = "0.6.11", features = ["csr"] }
shared = { path = "../shared" }
http = "1.2.0"
tonic-web-wasm-client = "0.6.1"
console_error_panic_hook = "0.1.7"
