[package]
name = "hydric"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
state = { path = "../state" }
mesic = { path = "../mesic" }
tonic-web-wasm-client = "0.7.0"
wasm-bindgen = "0.2.100"
egui = "0.31.1"
eframe = { version = "0.31.1", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
] }
log = "0.4.27"
wasm-bindgen-futures = "0.4.50"
strum = "0.27.1"
cpal = { path = "../vendor/cpal", features = ["wasm-bindgen"] }
poll-promise = { version = "0.3.0", features = ["web"] }
ordered-float = "5.0.0"
dasp_signal = "0.11.0"
dasp_frame = "0.11.0"
ecolor = "0.31.1"
egui_ltreeview = "0.2.0"
egui_plot = "0.32.1"
async-std = "1.13.1"
rfd = "0.15.3"
lazy_static = "1.5.0"
wasm_thread = "0.3.3"
crossbeam-channel = "0.5.15"
futures = "0.3.31"
web-sys = { version = "0.3.77", features = [
    "MediaDevices",
    "MediaStream",
    "MediaStreamConstraints",
    "Navigator",
    "Window",
    "MediaRecorder",
    "MediaRecorderOptions",
    "Blob",
    "BlobEvent",
] }
js-sys = "0.3.77"
ringbuffer = "0.15.0"
dasp_rms = "0.11.0"
dasp_ring_buffer = "0.11.0"
tonic = { version = "0.13.1", default-features = false }
egui_fancy_knob = "0.2.0"
egui_fader = "0.1.2"
egui-snarl = { path = "../vendor/egui-snarl" }

[features]
# Displays some extra debug information in the UI.
extra_debug = []
