[package]
name = "state"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.4"
ordered-float = "5.0.0"
shared = { path = "../shared" }
tonic = { version = "0.12.3", default-features = false, features = ["codegen", "prost"] }
local_macro = { path = "../local_macro" }
log = "0.4.27"
strum = "0.27.1"

[build-dependencies]
tonic-build = { version = "0.12.3", default-features = false, features = ["prost"] }
