[package]
name = "xeric"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
tonic = "0.13.1"
tokio = { version = "1.44.2", features = ["fs", "io-util", "rt-multi-thread"] }
anyhow = "1.0.95"
tonic-web = "0.13.1"
state = { path = "../state" }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors"] }
http = "1.2.0"
mesic = { path = "../mesic" }
hound = "3.5.1"
dasp_frame = "0.11.0"
log = "0.4.27"
pretty_env_logger = "0.5.0"
prost = "0.13.4"
itertools = "0.14.0"
