[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.4"
tonic = { version = "0.13.1", default-features = false, features = ["codegen", "prost"] }
strum = { version = "0.27.0", features = ["strum_macros", "derive"] }
byteorder = "1.5.0"
ordered-float = "5.0.0"
lazy_static = "1.5.0"
local_macro = { path = "../local_macro" }
web-sys = { version = "0.3.77", features = ["console"] }

[build-dependencies]
tonic-build = { version = "0.13.1", default-features = false, features = ["prost"] }
