#!/bin/bash
set -eux # Note: pipefail doesn't seem to work on Asahi? So use chained commands.
cargo fmt -p shared && cargo check -p shared && cargo check -p shared --target=wasm32-unknown-unknown &&
  cargo fmt -p mesic && cargo check -p mesic && cargo check -p mesic --target=wasm32-unknown-unknown &&
  cargo fmt -p state && cargo check -p state && cargo check -p state --target=wasm32-unknown-unknown &&
  cargo fmt -p hydric && cargo check -p hydric --target=wasm32-unknown-unknown &&
  cargo fmt -p xeric && cargo check -p xeric
