#!/bin/bash
set -eux # Note: pipefail doesn't seem to work on Asahi? So use chained commands.
cd shared && cargo fmt && cargo check && cargo check --target=wasm32-unknown-unknown && \
cd .. && \
cd mesic && cargo fmt && cargo check && cargo check --target=wasm32-unknown-unknown && \
cd .. && \
cd hydric && cargo fmt && cargo check --target=wasm32-unknown-unknown && leptosfmt * && \
cd .. && \
cd xeric && cargo fmt && cargo check && \
cd ..
